# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          PG_HOST: localhost
          PG_USER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test
          AWS_S3_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
          AWS_S3_BUCKET: example_s3_bucket
          AWS_S3_REGION: us-west-2
          AWS_S3_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYzEXAMPLEKEY
          BASE_ECPM: 400
          BUFFER_ENABLED: false
          DEFAULT_HOST: codefund.io
          ENABLED_FEATURES: jobs
          HUBSPOT_ENABLED: false
          PARALLEL_WORKERS: 1
          PG_TIMEOUT_IN_SECONDS: 3
          RAILS_MAX_THREADS: 10
          REDIS_CACHE_URL: redis://127.0.0.1:6379
          REDIS_QUEUE_URL: redis://127.0.0.1:6379
          SCOUT_SAMPLE_RATE: 0.3
          DATABASE_URL: "postgres://ubuntu@localhost:5432/code_fund_ads_test"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:11.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: code_fund_ads_test
      - image: circleci/redis:5.0.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: restore bundler cache
          keys:
            - cf-bundler-{{ checksum "Gemfile.lock" }}
            - cf-bundler-

      - restore_cache:
          name: restore yarn cache
          keys:
            - cf-yarn-{{ checksum "yarn.lock" }}
            - cf-yarn-

      - run: sudo apt-get update
      - run: sudo apt-get install -y postgresql-client
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash

      - run:
          name: update bundler
          command: |
            gem install bundler:2.0.1

      - run:
          name: install gem dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          name: save bundler cache
          paths:
            - ./vendor/bundle
          key: cf-bundler-{{ checksum "Gemfile.lock" }}

      - run:
          name: install yarn dependencies
          command: |
            yarn install --ignore-engines --frozen-lockfile

      - save_cache:
          name: save yarn cache
          paths:
            - ~/.cache/yarn
          key: cf-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Set up DB
          command: bundle exec rails db:drop db:create db:structure:load --trace

      - run:
          name: run tests
          command: bundle exec rails test

      - run:
          name: run system tests
          command: bundle exec rails test:system

      - run:
          name: run standardrb check
          command: bundle exec standardrb --format progress

      - run:
          name: run prettier-standard check
          command: yarn run --ignore-engines prettier-standard --check 'app/**/*.js'
