# IMPORTANT: All application enums should be defined in this file
#
# They will be made available to the application via: config/initializers/enums.rb
# ...and will be exposed uner the ENUMS module
#
# NOTE: Entries in this file can be either key/value or a simple list
#
# Examples
#
#   RATINGS:
#     gold: happy
#     silver: satisfied
#     bronze: sad
#
#   The YAML above will be converted to the following enums
#
#   pry>ENUMS::RATINGS::GOLD       # happy
#   pry>ENUMS::RATINGS::HAPPY      # gold
#   pry>ENUMS::RATINGS::SILVER     # satisfied
#   pry>ENUMS::RATINGS::SATISFIED  # silver
#   pry>ENUMS::RATINGS::BRONZE     # sad
#   pry>ENUMS::RATINGS::SAD        # bronze
#
#   ENUMs also supports the following helper methods
#
#   pry>ENUMS::RATINGS.keys             # [gold, silver, bronze]
#   pry>ENUMS::RATINGS.values           # [happy, satisfied, sad]
#   pry>ENUMS::RATINGS.happy? :gold     # true
#   pry>ENUMS::RATINGS.happy? :bronze   # false
#   pry>ENUMS::RATINGS["happy"]         # gold
#   pry>ENUMS::RATINGS["gold"]          # happy
#
#   ----------------------------------------------------------------------------
#
#   USER_ROLES:
#     - administrator
#     - advertiser
#     - publisher
#
#   The YAML above will be converted to the following enums
#
#   pry>ENUMS::USER_ROLES::ADMINISTRATOR # administrator
#   pry>ENUMS::USER_ROLES::ADVERTISER    # advertiser
#   pry>ENUMS::USER_ROLES::PUBLISHER     # publisher
#
#   pry>ENUMS::USER_ROLES.keys                          # [administrator, advertiser, publisher]
#   pry>ENUMS::USER_ROLES.values                        # [administrator, advertiser, publisher]
#   pry>ENUMS::USER_ROLES.administrator? :administrator # true
#   pry>ENUMS::USER_ROLES.administrator? :publisher     # false
#   pry>ENUMS::USER_ROLES["administrator"]              # administrator
#
#   ----------------------------------------------------------------------------
#
#   CAMPAIGN_STATUSES:
#     1: pending
#     2: active
#     3: archived
#
#   The YAML above will be converted to the following enums
#
#   pry>ENUMS::CAMPAIGN_STATUSES::PENDING    # 1
#   pry>ENUMS::CAMPAIGN_STATUSES::ACTIVE     # 2
#   pry>ENUMS::CAMPAIGN_STATUSES::ARCHIVED   # 3
#
#   pry>ENUMS::CAMPAIGN_STATUSES.keys        # [1, 2, 3]
#   pry>ENUMS::CAMPAIGN_STATUSES.values      # [pending, active, archived]
#   pry>ENUMS::CAMPAIGN_STATUSES.pending? 1  # true
#   pry>ENUMS::CAMPAIGN_STATUSES.pending? 2  # false
#   pry>ENUMS::CAMPAIGN_STATUSES["active"]   # 2
#   pry>ENUMS::CAMPAIGN_STATUSES[2]          # active
#

BLOCK_LIST:
  - cstream1.com
  - blockedurl.test

ORGANIZATION_ROLES:
  - administrator
  - member
  - owner

USER_ROLES:
  - administrator
  - advertiser
  - employer
  - publisher

USER_STATUSES:
  - active
  - blacklisted

USER_STATUS_COLORS:
  active: success
  blacklisted: dark

CAMPAIGN_STATUSES:
  - pending
  - active
  - archived

CAMPAIGN_STATUS_COLORS:
  pending: warning
  active: success
  archived: secondary
COUPON_TYPES:
  - percentage

CREATIVE_TYPES:
  - standard
  - sponsor

CREATIVE_STATUSES:
  - pending
  - active
  - archived

PROPERTY_TYPES:
  - website
  - repository
  - newsletter

PROPERTY_STATUSES:
  - pending
  - active
  - rejected
  - archived
  - blacklisted

PROPERTY_STATUS_COLORS:
  pending: warning
  active: success
  rejected: danger
  archived: muted
  blacklisted: dark

PROPERTY_RESPONSIVE_BEHAVIORS:
  - none
  - footer
  - hide

SCHEDULED_ORGANIZATION_REPORT_DATASETS:
  - current_month
  - past_7_days
  - past_30_days
  - yesterday

SCHEDULED_ORGANIZATION_REPORT_FREQUENCIES:
  - daily
  - weekly

# SEE: app/analyzers/creative_image_analyzer.rb
IMAGE_FORMATS:
  # 20x20, 40x40
  - icon

  # 200x200
  - small

  # 260x200
  - large

  # 512x320
  - wide

  # 400x40 svg
  - sponsor

  - unknown

IMAGE_CONTENT_TYPES:
  - image/gif
  - image/jpeg
  - image/png

IMPRESSION_CODES:
  - ok
  - property_inactive
  - impression_count_exceeded
  - no_possible_ads

RESERVED_ORGANIZATION_NAMES:
  - codefund

ORGANIZATION_TRANSACTION_TYPES:
  - debit
  - credit

ORGANIZATION_SEARCH_DIRECTIONS:
  - positive
  - negative
  - zero

JOB_PLANS:
  - monthly
  - prepaid

JOB_OFFERS:
  - premium_placement
  - code_fund_ads
  - read_the_docs_ads

JOB_TYPES:
  - full_time
  - part_time

JOB_STATUSES:
  - pending
  - active
  - archived
  - abandoned

JOB_STATUS_COLORS:
  pending: warning
  active: success
  archived: muted
  abandoned: danger

JOB_SOURCES:
  - internal
  - remoteok
  - github

# SEE: https://dev.maxmind.com/geoip/legacy/codes/iso3166/
COUNTRIES:
  #A1: Anonymous Proxy
  #A2: Satellite Provider
  #O1: Other Country
  AF: Afghanistan
  AX: Aland Islands
  AL: Albania
  DZ: Algeria
  AS: American Samoa
  AD: Andorra
  AO: Angola
  AI: Anguilla
  AQ: Antarctica
  AG: Antigua and Barbuda
  AR: Argentina
  AM: Armenia
  AW: Aruba
  AP: Asia/Pacific Region
  AU: Australia
  AT: Austria
  AZ: Azerbaijan
  BS: Bahamas
  BH: Bahrain
  BD: Bangladesh
  BB: Barbados
  BY: Belarus
  BE: Belgium
  BZ: Belize
  BJ: Benin
  BM: Bermuda
  BT: Bhutan
  BO: Bolivia
  BQ: Bonaire, Saint Eustatius and Saba
  BA: Bosnia and Herzegovina
  BW: Botswana
  BV: Bouvet Island
  BR: Brazil
  IO: British Indian Ocean Territory
  BN: Brunei Darussalam
  BG: Bulgaria
  BF: Burkina Faso
  BI: Burundi
  KH: Cambodia
  CM: Cameroon
  CA: Canada
  CV: Cape Verde
  KY: Cayman Islands
  CF: Central African Republic
  TD: Chad
  CL: Chile
  CN: China
  CX: Christmas Island
  CC: Cocos (Keeling) Islands
  CO: Colombia
  KM: Comoros
  CG: Congo
  CD: Congo, The Democratic Republic of the
  CK: Cook Islands
  CR: Costa Rica
  CI: Cote d'Ivoire
  HR: Croatia
  CU: Cuba
  CW: Curacao
  CY: Cyprus
  CZ: Czech Republic
  DK: Denmark
  DJ: Djibouti
  DM: Dominica
  DO: Dominican Republic
  EC: Ecuador
  EG: Egypt
  SV: El Salvador
  GQ: Equatorial Guinea
  ER: Eritrea
  EE: Estonia
  ET: Ethiopia
  EU: Europe
  FK: Falkland Islands (Malvinas)
  FO: Faroe Islands
  FJ: Fiji
  FI: Finland
  FR: France
  GF: French Guiana
  PF: French Polynesia
  TF: French Southern Territories
  GA: Gabon
  GM: Gambia
  GE: Georgia
  DE: Germany
  GH: Ghana
  GI: Gibraltar
  GR: Greece
  GL: Greenland
  GD: Grenada
  GP: Guadeloupe
  GU: Guam
  GT: Guatemala
  GG: Guernsey
  GN: Guinea
  GW: Guinea-Bissau
  GY: Guyana
  HT: Haiti
  HM: Heard Island and McDonald Islands
  VA: Holy See (Vatican City State)
  HN: Honduras
  HK: Hong Kong
  HU: Hungary
  IS: Iceland
  IN: India
  ID: Indonesia
  IR: Iran, Islamic Republic of
  IQ: Iraq
  IE: Ireland
  IM: Isle of Man
  IL: Israel
  IT: Italy
  JM: Jamaica
  JP: Japan
  JE: Jersey
  JO: Jordan
  KZ: Kazakhstan
  KE: Kenya
  KI: Kiribati
  KP: Korea, Democratic People's Republic of
  KR: Korea, Republic of
  KW: Kuwait
  KG: Kyrgyzstan
  LA: Lao People's Democratic Republic
  LV: Latvia
  LB: Lebanon
  LS: Lesotho
  LR: Liberia
  LY: Libyan Arab Jamahiriya
  LI: Liechtenstein
  LT: Lithuania
  LU: Luxembourg
  MO: Macao
  MK: Macedonia
  MG: Madagascar
  MW: Malawi
  MY: Malaysia
  MV: Maldives
  ML: Mali
  MT: Malta
  MH: Marshall Islands
  MQ: Martinique
  MR: Mauritania
  MU: Mauritius
  YT: Mayotte
  MX: Mexico
  FM: Micronesia, Federated States of
  MD: Moldova, Republic of
  MC: Monaco
  MN: Mongolia
  ME: Montenegro
  MS: Montserrat
  MA: Morocco
  MZ: Mozambique
  MM: Myanmar
  NA: Namibia
  NR: Nauru
  NP: Nepal
  NL: Netherlands
  NC: New Caledonia
  NZ: New Zealand
  NI: Nicaragua
  NE: Niger
  NG: Nigeria
  NU: Niue
  NF: Norfolk Island
  MP: Northern Mariana Islands
  "NO": Norway
  OM: Oman
  PK: Pakistan
  PW: Palau
  PS: Palestinian Territory
  PA: Panama
  PG: Papua New Guinea
  PY: Paraguay
  PE: Peru
  PH: Philippines
  PN: Pitcairn
  PL: Poland
  PT: Portugal
  PR: Puerto Rico
  QA: Qatar
  RE: Reunion
  RO: Romania
  RU: Russian Federation
  RW: Rwanda
  BL: Saint Barthelemy
  SH: Saint Helena
  KN: Saint Kitts and Nevis
  LC: Saint Lucia
  MF: Saint Martin
  PM: Saint Pierre and Miquelon
  VC: Saint Vincent and the Grenadines
  WS: Samoa
  SM: San Marino
  ST: Sao Tome and Principe
  SA: Saudi Arabia
  SN: Senegal
  RS: Serbia
  SC: Seychelles
  SL: Sierra Leone
  SG: Singapore
  SX: Sint Maarten
  SK: Slovakia
  SI: Slovenia
  SB: Solomon Islands
  SO: Somalia
  ZA: South Africa
  GS: South Georgia and the South Sandwich Islands
  SS: South Sudan
  ES: Spain
  LK: Sri Lanka
  SD: Sudan
  SR: Suriname
  SJ: Svalbard and Jan Mayen
  SZ: Swaziland
  SE: Sweden
  CH: Switzerland
  SY: Syrian Arab Republic
  TW: Taiwan
  TJ: Tajikistan
  TZ: Tanzania, United Republic of
  TH: Thailand
  TL: Timor-Leste
  TG: Togo
  TK: Tokelau
  TO: Tonga
  TT: Trinidad and Tobago
  TN: Tunisia
  TR: Turkey
  TM: Turkmenistan
  TC: Turks and Caicos Islands
  TV: Tuvalu
  UG: Uganda
  UA: Ukraine
  AE: United Arab Emirates
  GB: United Kingdom
  US: United States
  UM: United States Minor Outlying Islands
  UY: Uruguay
  UZ: Uzbekistan
  VU: Vanuatu
  VE: Venezuela
  VN: Vietnam
  VG: Virgin Islands, British
  VI: Virgin Islands, U.S.
  WF: Wallis and Futuna
  EH: Western Sahara
  YE: Yemen
  ZM: Zambia
  ZW: Zimbabwe

# SEE: https://www.msci.com/market-classification
DEVELOPED_MARKET_COUNTRIES:
  AU: Australia
  AT: Austria
  BE: Belgium
  CA: Canada
  DK: Denmark
  FI: Finland
  FR: France
  DE: Germany
  HK: Hong Kong
  IE: Ireland
  IL: Israel
  IT: Italy
  JP: Japan
  NL: Netherlands
  NZ: New Zealand
  "NO": Norway
  PT: Portugal
  SG: Singapore
  ES: Spain
  SE: Sweden
  CH: Switzerland
  GB: United Kingdom
  US: United States

EMERGING_MARKET_COUNTRIES:
  BR: Brazil
  CL: Chile
  CN: China
  CO: Colombia
  CZ: Czech Republic
  EG: Egypt
  GR: Greece
  HU: Hungary
  IN: India
  ID: Indonesia
  KR: Korea, Republic of
  MY: Malaysia
  MX: Mexico
  PK: Pakistan
  PE: Peru
  PH: Philippines
  PL: Poland
  QA: Qatar
  RU: Russian Federation
  ZA: South Africa
  TW: Taiwan
  TH: Thailand
  TR: Turkey
  AE: United Arab Emirates

LANGUAGES:
  - Albanian
  - Armenian
  - Azeri
  - Belarusian
  - Bosnian
  - Bulgarian
  - Chinese
  - Croatian
  - Czech
  - Danish
  - Divehi
  - Dutch
  - English
  - Estonian
  - FYRO Macedonian
  - Faroese
  - Farsi
  - Finnish
  - French
  - Galician
  - Georgian
  - German
  - Greek
  - Hebrew
  - Hindi
  - Hungarian
  - Icelandic
  - Indonesian
  - Italian
  - Japanese
  - Kazakh
  - Korean
  - Kyrgyz
  - Latvian
  - Lithuanian
  - Malay
  - Maltese
  - Maori
  - Mongolian
  - Norwegian
  - Pashto
  - Polish
  - Portuguese
  - Romanian
  - Russian
  - Serbian
  - Slovak
  - Slovenian
  - Spanish
  - Swahili
  - Swedish
  - Syriac
  - Tagalog
  - Thai
  - Turkish
  - Ukrainian
  - Urdu
  - Uzbek
  - Vietnamese
  - Zulu

KEYWORDS:
  # topics
  "Android":
    - android
  "Angular":
    - angular
    - angularjs
  "Backend":
    - architecture
    - backend
    - full stack
    - full-stack
  "Blockchain":
    - blockchain
    - solidity
    - cryptography
  "CSS & Design":
    - css
    - design
    - ui
    - ux
  "Cryptography":
    - cryptography
  "Database":
    - full stack
    - full-stack
    - graphql
    - mongodb
    - postgresql
    - postgres
    - mysql
  "DevOps":
    - devops
    - kubernetes
    - serverless
  "Developer Resources":
    - technical writing
  "Frontend":
    - front end
    - frontend
    - full stack
    - full-stack
    - javascript
    - vue
    - react
    - angular
    - angularjs
  "Game Development":
    - game design
    - game dev
    - gaming
    - unity
  "Hybrid & Mobile Web":
    - electron
  "IoT":
    - iot
    - internet of things
    - wireless
  "Machine Learning":
    - machine learning
  "React":
    - react
    - react native
    - reactnative
  "Security":
    - infosec
    - network security
  "Serverless":
    - architecture
    - cloud
    - devops
    - kubernetes
    - microservices
    - serverless
  "Virtual Reality":
    - virtual reality
    - vr
  "VueJS":
    - vuejs
    - vue
  "iOS":
    - ios

  # programming languages
  ".NET":
    - dot net
    - dotnet
    - .net
    - windows
  "C":
    - c
    - c plus plus
  "C#":
    - c#
  "C++":
    - c++
    - c plus plus
  "D":
    - d
  "Dart":
    - dart
  "Erlang":
    - elixir
    - erlang
    - phoenix
  "F#":
    - f sharp
    - f#
  "Go":
    - go
    - golang
  "Groovy":
    - groovy
  "Haskell":
    - haskell
  "Java":
    - android
    - java
  "JavaScript":
    - angularjs
    - electron
    - es6
    - graphql
    - javascript
    - meteor js
    - node
    - node js
    - node.js
  "Julia":
    - julia
  "Kotlin":
    - kotlin
  "Objective-C":
    - objective-c
    - objective c
    - obj c
  "PHP":
    - drupal
    - laravel
    - php
  "PL/SQL":
    - pl/sql
    - plsql
  "Python":
    - django
    - python
  "Q":
    - q
  "R":
    - r
  "Ruby":
    - rails
    - ruby
  "Rust":
    - rust
  "Scala":
    - scala
  "Swift":
    - swift
  "Other":
    - other
