test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: S3
  access_key_id: <%= ENV["AWS_S3_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_S3_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AWS_S3_REGION"] %>
  bucket: <%= ENV["AWS_S3_BUCKET"] %>

amazon:
  service: S3
  access_key_id: <%= ENV["AWS_S3_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_S3_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AWS_S3_REGION"] %>
  bucket: <%= ENV["AWS_S3_BUCKET"] %>
